### ISSUE TITLE
Picking up while "Things that are here" window shown locks up QT version 

### ISSUE THREAD

**Issue by aberent** [NetHack/NetHack#400]
Running QT nethack on Ubuntu, versions:

Unix NetHack Version 3.6.6-0 post-release - last build Sat Oct 10 12:23:21 2020
Ubuntu 20.04.1 LTS

1, My character steps on a tile with multiple object; a window with the first line "Things that are here" is displayed. 
2. (without dismissing this dialog) I press comma to pick up items. A new dialog is displayed for item selection.
3. I select some items and close the second dialog
4. I attempt to dismiss the "Things that are here" message box. This doesn't work, and no other commands work.

I can't find a way of continuing, and the only way of closing nethack is to kill it from a terminal or the system monitor.

**Comment by nhmall** [comment]
Have you tried the NetHack-3.7 branch that is under development? There's been a number of Qt commits there and perhaps it has been addressed. Development focuses on that branch and very little activity beyond security fixes happen on the NetHack-3.6 branch these days.

**Comment by aberent** [comment]
Still a problem on today's build of 3.7:

Unix NetHack Version 3.7.0-23 Work-in-progress - last build Wed Oct 21 11:35:49 2020
(dde561810d6fef8751f1794753dff889c0def3d3,branch:Nethack-3.7).
